export const MOCK_REVIEWS = [
  {
    id: 'mock-1',
    reviewer_name: 'Marie Dupont',
    rating: 5,
    comment: 'Excellent restaurant ! Le service est impeccable et les plats sont délicieux. Je recommande vivement le menu du jour.',
    review_created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    status: 'response_pending',
    photo_urls: [
      'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=300&h=300&fit=crop',
      'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=300&h=300&fit=crop',
    ],
    responses: [{
      id: 'resp-1',
      ai_generated_text: "Merci beaucoup Marie pour votre avis chaleureux ! Nous sommes ravis que vous ayez apprécié notre service et nos plats. Le menu du jour est en effet l'une de nos fiertés. Au plaisir de vous revoir très bientôt !",
      final_text: null,
      status: 'draft',
    }],
  },
  {
    id: 'mock-2',
    reviewer_name: 'Thomas Laurent',
    rating: 2,
    comment: "Attente beaucoup trop longue pour être servi. Le plat était correct mais froid à l'arrivée. Dommage.",
    review_created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    status: 'response_pending',
    photo_urls: [
      'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=300&h=300&fit=crop',
    ],
    responses: [{
      id: 'resp-2',
      ai_generated_text: "Bonjour Thomas, nous sommes sincèrement désolés pour cette expérience décevante. Le temps d'attente que vous décrivez ne reflète pas nos standards habituels. Nous avons pris des mesures pour améliorer notre service. Nous aimerions vous offrir un repas pour nous rattraper. N'hésitez pas à nous contacter directement.",
      final_text: null,
      status: 'draft',
    }],
  },
  {
    id: 'mock-3',
    reviewer_name: 'Sophie Martin',
    rating: 1,
    comment: "Arnaque totale ! On nous a facturé des plats qu'on n'a jamais commandés. Le responsable a refusé de corriger l'addition. Scandaleux, je vais porter plainte.",
    review_created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    status: 'response_pending',
    is_dangerous: true,
    responses: [{
      id: 'resp-3',
      ai_generated_text: "Bonjour Sophie, nous sommes sincèrement désolés pour cette situation qui ne reflète pas nos valeurs. Nous prenons votre signalement très au sérieux et souhaitons rectifier cette erreur immédiatement. Pourriez-vous nous contacter directement au restaurant afin que nous puissions examiner votre addition et vous rembourser si nécessaire ?",
      final_text: null,
      status: 'draft',
    }],
  },
  {
    id: 'mock-4',
    reviewer_name: 'Pierre Moreau',
    rating: 5,
    comment: 'La meilleure pizza de la ville ! Pâte fine et croustillante, ingrédients frais. On y retourne chaque semaine.',
    review_created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'responded',
    responses: [{
      id: 'resp-4',
      ai_generated_text: "Merci Pierre, quel beau compliment ! Notre pizzaïolo sera ravi de l'apprendre.",
      final_text: "Merci Pierre, quel beau compliment ! Notre pizzaïolo sera ravi de l'apprendre. C'est un plaisir de vous compter parmi nos fidèles clients. À très vite !",
      status: 'published',
    }],
  },
  {
    id: 'mock-5',
    reviewer_name: 'Camille Bernard',
    rating: 4,
    comment: "Bonne expérience dans l'ensemble, cuisine savoureuse et cadre sympa. Petit bémol sur l'attente à l'entrée, on aurait pu être accueillis plus rapidement.",
    review_created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'response_pending',
    is_dangerous: false,
    responses: [{
      id: 'resp-5',
      ai_generated_text: "Merci Camille pour votre retour ! Nous sommes ravis que la cuisine et le cadre vous aient plu. Votre remarque sur l'accueil est bien notée, nous travaillons à améliorer ce point. À très bientôt !",
      final_text: null,
      status: 'draft',
    }],
  },
  {
    id: 'mock-6',
    reviewer_name: 'Julien Petit',
    rating: 3,
    comment: "Bonne cuisine mais un peu bruyant. Difficile d'avoir une conversation tranquille.",
    review_created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'responded',
    responses: [{
      id: 'resp-6',
      ai_generated_text: "Merci Julien pour votre avis honnête.",
      final_text: "Merci Julien pour votre avis honnête ! Nous comprenons que l'ambiance sonore peut être un point important. Nous avons récemment installé des panneaux acoustiques pour améliorer le confort. Venez tester lors de votre prochaine visite !",
      status: 'published',
    }],
  },
  {
    id: 'mock-7',
    reviewer_name: 'Emma Leroy',
    rating: 5,
    comment: "Brunch du dimanche absolument parfait ! Les pancakes sont incroyables et le jus d'orange frais un vrai délice.",
    review_created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'response_pending',
    photo_urls: [
      'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=300&h=300&fit=crop',
      'https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=300&h=300&fit=crop',
      'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=300&h=300&fit=crop',
    ],
    responses: [{
      id: 'resp-7',
      ai_generated_text: "Merci Emma pour ce magnifique retour ! Notre brunch du dimanche est préparé avec amour chaque semaine. Les pancakes sont faits maison et le jus d'orange pressé à la minute. Nous sommes ravis que vous ayez passé un bon moment. À dimanche prochain peut-être !",
      final_text: null,
      status: 'draft',
    }],
  },
]

export const MOCK_BUSINESSES = [
  {
    id: 'biz-1',
    business_name: 'Le Petit Bistrot',
    address: '12 Rue de la Paix, 75002 Paris',
    business_type: 'Restaurant',
    is_active: true,
    response_mode: 'validation',
    tone_preference: 'professionnel',
    custom_instructions: 'Toujours mentionner notre programme de fidélité et proposer un café offert pour les avis négatifs.',
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'biz-2',
    business_name: 'Pizza Roma',
    address: '45 Avenue des Champs-Élysées, 75008 Paris',
    business_type: 'Pizzeria',
    is_active: true,
    response_mode: 'auto',
    tone_preference: 'amical',
    custom_instructions: '',
    created_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
]
