export const MOCK_REVIEWS = [
  {
    id: 'mock-1',
    reviewer_name: 'Marie Dupont',
    rating: 5,
    comment: 'Excellent restaurant ! Le service est impeccable et les plats sont délicieux. Je recommande vivement le menu du jour.',
    review_created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    status: 'response_pending',
    photo_urls: [
      'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=300&h=300&fit=crop',
      'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=300&h=300&fit=crop',
    ],
    responses: [{
      id: 'resp-1',
      ai_generated_text: "Merci beaucoup Marie pour votre avis chaleureux ! Nous sommes ravis que vous ayez apprécié notre service et nos plats. Le menu du jour est en effet l'une de nos fiertés. Au plaisir de vous revoir très bientôt !",
      final_text: null,
      status: 'draft',
    }],
  },
  {
    id: 'mock-2',
    reviewer_name: 'Thomas Laurent',
    rating: 2,
    comment: "Attente beaucoup trop longue pour être servi. Le plat était correct mais froid à l'arrivée. Dommage.",
    review_created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    status: 'response_pending',
    photo_urls: [
      'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=300&h=300&fit=crop',
    ],
    responses: [{
      id: 'resp-2',
      ai_generated_text: "Bonjour Thomas, nous sommes sincèrement désolés pour cette expérience décevante. Le temps d'attente que vous décrivez ne reflète pas nos standards habituels. Nous avons pris des mesures pour améliorer notre service. Nous aimerions vous offrir un repas pour nous rattraper. N'hésitez pas à nous contacter directement.",
      final_text: null,
      status: 'draft',
    }],
  },
  {
    id: 'mock-3',
    reviewer_name: 'Sophie Martin',
    rating: 4,
    comment: 'Très bon rapport qualité-prix. Cadre agréable et personnel souriant. Petit bémol sur le dessert.',
    review_created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    status: 'responded',
    responses: [{
      id: 'resp-3',
      ai_generated_text: "Merci Sophie pour votre retour ! Nous sommes heureux que l'ambiance et le service vous aient plu.",
      final_text: "Merci Sophie pour votre retour ! Nous sommes heureux que l'ambiance et le service vous aient plu. Nous prenons note de votre remarque sur le dessert et travaillons à améliorer notre carte. À bientôt !",
      status: 'published',
    }],
  },
  {
    id: 'mock-4',
    reviewer_name: 'Pierre Moreau',
    rating: 5,
    comment: 'La meilleure pizza de la ville ! Pâte fine et croustillante, ingrédients frais. On y retourne chaque semaine.',
    review_created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'responded',
    responses: [{
      id: 'resp-4',
      ai_generated_text: "Merci Pierre, quel beau compliment ! Notre pizzaïolo sera ravi de l'apprendre.",
      final_text: "Merci Pierre, quel beau compliment ! Notre pizzaïolo sera ravi de l'apprendre. C'est un plaisir de vous compter parmi nos fidèles clients. À très vite !",
      status: 'published',
    }],
  },
  {
    id: 'mock-5',
    reviewer_name: 'Camille Bernard',
    rating: 1,
    comment: "Très déçue. Réservation perdue, on a dû attendre 45 minutes. En plus la note était incorrecte.",
    review_created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'response_pending',
    responses: [{
      id: 'resp-5',
      ai_generated_text: "Bonjour Camille, nous vous présentons nos plus sincères excuses pour cette expérience inacceptable. La perte de votre réservation et l'erreur de facturation ne sont pas tolérables. Nous aimerions vous inviter pour un dîner offert afin de nous rattraper. Pourriez-vous nous contacter au restaurant ?",
      final_text: null,
      status: 'draft',
    }],
  },
  {
    id: 'mock-6',
    reviewer_name: 'Julien Petit',
    rating: 3,
    comment: "Bonne cuisine mais un peu bruyant. Difficile d'avoir une conversation tranquille.",
    review_created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'responded',
    responses: [{
      id: 'resp-6',
      ai_generated_text: "Merci Julien pour votre avis honnête.",
      final_text: "Merci Julien pour votre avis honnête ! Nous comprenons que l'ambiance sonore peut être un point important. Nous avons récemment installé des panneaux acoustiques pour améliorer le confort. Venez tester lors de votre prochaine visite !",
      status: 'published',
    }],
  },
  {
    id: 'mock-7',
    reviewer_name: 'Emma Leroy',
    rating: 5,
    comment: "Brunch du dimanche absolument parfait ! Les pancakes sont incroyables et le jus d'orange frais un vrai délice.",
    review_created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'response_pending',
    photo_urls: [
      'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=300&h=300&fit=crop',
      'https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=300&h=300&fit=crop',
      'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=300&h=300&fit=crop',
    ],
    responses: [{
      id: 'resp-7',
      ai_generated_text: "Merci Emma pour ce magnifique retour ! Notre brunch du dimanche est préparé avec amour chaque semaine. Les pancakes sont faits maison et le jus d'orange pressé à la minute. Nous sommes ravis que vous ayez passé un bon moment. À dimanche prochain peut-être !",
      final_text: null,
      status: 'draft',
    }],
  },
]

export const MOCK_BUSINESSES = [
  {
    id: 'biz-1',
    business_name: 'Le Petit Bistrot',
    address: '12 Rue de la Paix, 75002 Paris',
    business_type: 'Restaurant',
    is_active: true,
    response_mode: 'validation',
    tone_preference: 'professionnel',
    custom_instructions: 'Toujours mentionner notre programme de fidélité et proposer un café offert pour les avis négatifs.',
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'biz-2',
    business_name: 'Pizza Roma',
    address: '45 Avenue des Champs-Élysées, 75008 Paris',
    business_type: 'Pizzeria',
    is_active: true,
    response_mode: 'auto',
    tone_preference: 'amical',
    custom_instructions: '',
    created_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
]
